---
info:
  title: Iotseeker
  description: Created by Jin Qian via the GitHub Connector
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/IoTSeeker
  x-cortex-tag: iotseeker
  x-cortex-type: service
  x-cortex-owners:
  - type: SLACK
    channel: soar
    notificationsEnabled: 'false'
  - type: SLACK
    channel: ask-infosec
    notificationsEnabled: 'false'
  - type: SLACK
    channel: exploit-dev
    notificationsEnabled: 'false'
  - type: SLACK
    channel: platform-delivery
    notificationsEnabled: 'false'
  - type: SLACK
    channel: invisible
    notificationsEnabled: 'false'
openapi: 3.0.1
servers:
- url: "/"
